#!/usr/bin/env bash

# Copyright 2019 Valentin Lahaye
#
# This work may be distributed and/or modified under the
# conditions of the LaTeX Project Public License, either version 1.3
# of this license or (at your option) any later version.
# The latest version of this license is in
#   http://www.latex-project.org/lppl.txt
# and version 1.3 or later is part of all distributions of LaTeX
# version 2005/12/01 or later.

set -euo pipefail
IFS=$"\n\t"

main() {
  local hash
  local hashRef
  local target="docs/curriculum-vitae.pdf"
  [[ -r "$target" ]] && hashRef="$(git hash-object "$target")"
  make dist
  hash="$(git hash-object "$target")"
  if [[ "$hashRef" != "$hash" ]]; then
    echo "Installed curriculum-vitae. Please review and stage the changes."
    exit 1
  fi
}

main "$@"
